export const ACTIVITY_TYPE_KEYWORDS: Record<string, string[]> = {
  "Food & Cooking": [
  "johnny cake",
  "johnny cake class",
  "conch salad",
  "conch salad class",
    "conch",
    "cook",
    "cooking",
    "class",
    "culinary",
    "restaurant",
    "cafe",
    "dining",
  ],
  "Sports": [
  "fly fishing",
  "fly fishing",
  "fly-fishing",
  "fly fishing lessons",
    "fly-fishing",
    "wake surf",
    "wake-surf",
  "wake surfing",
    "wake",
    "wakeboarding",
    "mountain biking",
  "mountain biking",
    "mountain bike",
    "mtb",
    "jet ski",
  "jet ski",
    "jetski",
    "jet-ski",
    "surf",
    "kayak",
    "fishing",
    "jet",
    "bike",
  ],
  "Relaxation / Wellness": [
  "island glow spa",
    "spa",
    "wellness",
    "massage",
    "yoga",
    "relax",
  ],
  "Nature": [
  "bird watching",
  "bird watching",
    "birdwatching",
    "island flats",
  "island flats tour",
    "flats",
    "wildlife",
    "nature",
    "eco",
    "bird",
  ],
  "Services / Other": [
  "healthcare",
    "clinic",
    "service",
    "services",
    "store",
    "shop",
  ],
  "Tours/Adventure": [
    "tour",
    "excursion",
    "guided",
    "sightseeing",
    "island tour",
    "boat tour",
    "island flats tour",
    "adventure"
  ],
}

export const ACTIVITY_TYPES = Object.keys(ACTIVITY_TYPE_KEYWORDS)
